name: test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # - name: Set up Deno
      #   uses: denoland/setup-deno@main
      - uses: ./
      # - name: Run tests
      #   run: |
      #     deno run --no-remote test.ts
