name: test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.25.2
      - name: Lint
        run: |
          deno fmt --check
          deno lint
      - name: Install npm packages
        uses: bahmutov/npm-install@v1
      - name: Check dist
        run: |
          yarn build
          git diff --exit-code
      - uses: ./
        with:
          path: |
            test.ts
          key: ${{ runner.os }}-${{ hashFiles('**/test.ts', '**/import_map.json') }}
          import-map: import_map.json
      - name: Run tests
        run: |
          deno run --cached-only --import-map=import_map.json test.ts
          deno run --cached-only https://deno.land/std@0.156.0/examples/welcome.ts
