name: test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # - name: Set up Deno
      #   uses: denoland/setup-deno@main
      - uses: uki00a/deno-cache-action@HEAD
      # - name: Run tests
      #   run: |
      #     deno run --no-remote test.ts
